---
version: '3'
 
services:
  server1:
     build: ./web_server
     restart: always
     networks:
       - set_exercise_bridge

  server2:
     build: ./web_server
     restart: always
     networks:
       - set_exercise_bridge

  server3:
     build: ./web_server
     restart: always
     networks:
       - set_exercise_bridge

  server4:
     build: ./web_server
     restart: always
     networks:
       - set_exercise_bridge
            
  web_balancer: 
     build: ./web_balancer
     restart: always
     ports:
       - "8081:80"    
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
     depends_on:
       - server1
       - server2
       - server3
       - server4

networks:
  set_exercise_bridge:


