---
version: '3'
 
services:
  server1:
     build: ./web_server
     environment:
       - SERVER_NAME=server1
     networks:
       - set_exercise_bridge
    
  server2:
     build: ./web_server
     environment:
       - SERVER_NAME=server2
     networks:
       - set_exercise_bridge
    
  server3:
     build: ./web_server    
     environment:
       - SERVER_NAME=server3
     networks:
       - set_exercise_bridge
    
  server4:
     build: ./web_server    
     environment:
       - SERVER_NAME=server4
     networks:
       - set_exercise_bridge
  
  web_balancer: 
     build: ./web_balancer
     ports:
       - "8081:80"    
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
     depends_on:
       - server1
       - server2
       - server3
       - server4

networks:
  set_exercise_bridge:


