---
version: '3'
 
services:
  server1:
     image: php:fpm
     environment:
       - SERVER_NAME=server1
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
    
  server2:
     image: php:fpm
     environment:
       - SERVER_NAME=server2
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
    
  server3:
     image: php:fpm
     environment:
       - SERVER_NAME=server3
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
    
  server4:
     image: php:fpm     
     environment:
       - SERVER_NAME=server4
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
  
  web_balancer: 
     image: nginx:alpine
     ports:
       - "8081:80"    
     networks:
       - set_exercise_bridge
     volumes:
       - ./web_server:/web
       - ./web_balancer/nginx.conf:/etc/nginx/nginx.conf
     depends_on:
       - server1
       - server2
       - server3
       - server4

networks:
  set_exercise_bridge:
